algoritmo "semnome"
// Função :
// Autor :
// Data : 23/12/2014
// Seção de Declarações 
var
   X,Y: inteiro
   procedimento soma (var A, B: inteiro)
   inicio
   
         A <- A + 1
         B <- B + 2
         escreval("Valor de A= ", A)
         escreval("Valor de B= ", B)
         escreval("Valor de A+B= ", A+B)
   
   fimprocedimento
   
inicio
// Seção de Comandos
   X <- 4
   Y <- 8
   Soma (X,Y)
   escreval("Valor de x = ", X)
   escreval("Valor de y= ", Y)
fimalgoritmo
